### ISSUE TITLE
Добавить логгер с возможностью уровня логгирования

### ISSUE THREAD

**Issue by donebd** [donebd/vscode-keypromoter#11]
Предварительно будем юзать:
https://www.npmjs.com/package/winston

Нужно вынести уровень логгов юзеру в проперти плагина, и подумать где хранить логги

**Comment by donebd** [comment]
Уровень логгов брать из https://github.com/donebd/vscode-keypromoter/issues/13

**Comment by Slava0135** [comment]
нужно использовать API https://code.visualstudio.com/api/references/vscode-api#window.createOutputChannel
