### ISSUE TITLE
Добавить настраиваемые проперти плагина

### ISSUE THREAD

**Issue by donebd** [donebd/vscode-keypromoter#13]
Что будет в пропертях:

1) Уровень лояльности - интервал нотификаций напоминания юзеру про конкретный шорткат. По дефолту хз мб 5?

2) Спсиок игнорируемых комманд - комманды которые юзер хочет нажимать ручками без шорткатов. Будет пополняться через кнопку Suspend warning for this command. Или ручками. По дефолту пустой.

3) Флаг предложения создания шорткатов для комманд, для которых нет шорткатов но юзер их тыкает ручками. Будет редактироваться ручками либо через кнопку в нотификации про добавление шортката. По дефолту включен

4) Уровень логгирования (надо подумать какие хотим). По дефолту Error (самый высокий)

5) Мб папка в которую писать логги? По дефолту будем писать наверное куда то в темы или надо погуглить куда вскод пишет логги по дефолту

**Comment by Targaseer** [comment]
Проперти залиты в мастер. Пока что в коде используется только 1.

**Comment by donebd** [comment]
Realized in https://github.com/donebd/vscode-keypromoter/pull/27
