### ISSUE TITLE
Подумать как сделать нотификашку покрасивше

### ISSUE THREAD

**Issue by donebd** [donebd/vscode-keypromoter#21]
Может как то выделять шорткат, и еще я бы подумал над более человекочитаемым представлением комманды, а то юзеру айдишник комманды не очень нативен

**Comment by Slava0135** [comment]
Насколько я понял, здесь нет поддержки Markdown или чего-нибудь еще

**Comment by ALTV2** [comment]
Да нет ни html, ни md

**Comment by ALTV2** [comment]
Сделал маппинг на +- нормальные названия

**Comment by donebd** [comment]
Realized in https://github.com/donebd/vscode-keypromoter/pull/34
